### PR TITLE
feat: Implement cpufactor and memoryminimum by cluster

### PR DESCRIPTION
**Pull request by lperdereau**

### CODE REVIEW

**Comment by lperdereau** [comment]
Draft, I have to patch auto indent fix

**Comment by lcaflc** [comment]
The cpu and memory factors are also used in the nodeevacuate action. This also must be modifed to use those configuration.
Better will be to add those configuration options to the cluster object so they are always available by all the actions.

**Comment by lcaflc** [comment]
Configuration template / documentation must also be updated accordingly. Moreover that you change the default value :)

**Comment by lcaflc** [comment]
I'm not a big fan of changing the options name from `node` to `node_factors` .  This is actually only the options available but this ca change. See better keep it same name for now.
This also prevent a breaking change in configuration.

**Comment by lperdereau** [comment]
> I'm not a big fan of changing the options name from `node` to `node_factors` . This is actually only the options available but this ca change. See better keep it same name for now. This also prevent a breaking change in configuration.

@lcaflc No problem, I'll change it, but I found that `node` is misleading about what it will do.

Moreover, I think before version 1 we can break the CLI, it's not "stable".
From semantic versioning spec:
```
Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.
```
[https://semver.org/#spec-item-9](https://semver.org/#spec-item-9)

**Review by lcaflc — APPROVED** [review]
seems good.

**Pull request merged**
